export type CountryInfo = {
  name: string;
  /** ISO 3166-1 alpha-2 */
  iso: string;
  /** Dial digits without + */
  dialCode: string;
  /** E.164-style calling code with + */
  phoneCode: string;
  /** Primary IANA timezone */
  timezone: string;
  /** ISO 4217 currency */
  currency: string;
};

/** Canonical country list (name, ISO, dial, timezone, currency). */
export const COUNTRY_LIST: CountryInfo[] = [
  { name: 'Afghanistan', iso: 'AF', dialCode: '93', phoneCode: '+93', timezone: 'Asia/Kabul', currency: 'AFN' },
  { name: 'Albania', iso: 'AL', dialCode: '355', phoneCode: '+355', timezone: 'Europe/Tirane', currency: 'ALL' },
  { name: 'Algeria', iso: 'DZ', dialCode: '213', phoneCode: '+213', timezone: 'Africa/Algiers', currency: 'DZD' },
  { name: 'Andorra', iso: 'AD', dialCode: '376', phoneCode: '+376', timezone: 'Europe/Andorra', currency: 'EUR' },
  { name: 'Angola', iso: 'AO', dialCode: '244', phoneCode: '+244', timezone: 'Africa/Luanda', currency: 'AOA' },
  { name: 'Antigua and Barbuda', iso: 'AG', dialCode: '1268', phoneCode: '+1268', timezone: 'America/Antigua', currency: 'XCD' },
  { name: 'Argentina', iso: 'AR', dialCode: '54', phoneCode: '+54', timezone: 'America/Argentina/Buenos_Aires', currency: 'ARS' },
  { name: 'Armenia', iso: 'AM', dialCode: '374', phoneCode: '+374', timezone: 'Asia/Yerevan', currency: 'AMD' },
  { name: 'Aruba', iso: 'AW', dialCode: '297', phoneCode: '+297', timezone: 'America/Aruba', currency: 'AWG' },
  { name: 'Australia', iso: 'AU', dialCode: '61', phoneCode: '+61', timezone: 'Australia/Sydney', currency: 'AUD' },
  { name: 'Austria', iso: 'AT', dialCode: '43', phoneCode: '+43', timezone: 'Europe/Vienna', currency: 'EUR' },
  { name: 'Azerbaijan', iso: 'AZ', dialCode: '994', phoneCode: '+994', timezone: 'Asia/Baku', currency: 'AZN' },
  { name: 'Bahamas', iso: 'BS', dialCode: '1242', phoneCode: '+1242', timezone: 'America/Nassau', currency: 'BSD' },
  { name: 'Bahrain', iso: 'BH', dialCode: '973', phoneCode: '+973', timezone: 'Asia/Bahrain', currency: 'BHD' },
  { name: 'Bangladesh', iso: 'BD', dialCode: '880', phoneCode: '+880', timezone: 'Asia/Dhaka', currency: 'BDT' },
  { name: 'Barbados', iso: 'BB', dialCode: '1246', phoneCode: '+1246', timezone: 'America/Barbados', currency: 'BBD' },
  { name: 'Belarus', iso: 'BY', dialCode: '375', phoneCode: '+375', timezone: 'Europe/Minsk', currency: 'BYN' },
  { name: 'Belgium', iso: 'BE', dialCode: '32', phoneCode: '+32', timezone: 'Europe/Brussels', currency: 'EUR' },
  { name: 'Belize', iso: 'BZ', dialCode: '501', phoneCode: '+501', timezone: 'America/Belize', currency: 'BZD' },
  { name: 'Benin', iso: 'BJ', dialCode: '229', phoneCode: '+229', timezone: 'Africa/Porto-Novo', currency: 'XOF' },
  { name: 'Bhutan', iso: 'BT', dialCode: '975', phoneCode: '+975', timezone: 'Asia/Thimphu', currency: 'BTN' },
  { name: 'Bolivia', iso: 'BO', dialCode: '591', phoneCode: '+591', timezone: 'America/La_Paz', currency: 'BOB' },
  { name: 'Bosnia and Herzegovina', iso: 'BA', dialCode: '387', phoneCode: '+387', timezone: 'Europe/Sarajevo', currency: 'BAM' },
  { name: 'Botswana', iso: 'BW', dialCode: '267', phoneCode: '+267', timezone: 'Africa/Gaborone', currency: 'BWP' },
  { name: 'Brazil', iso: 'BR', dialCode: '55', phoneCode: '+55', timezone: 'America/Sao_Paulo', currency: 'BRL' },
  { name: 'British Indian Ocean Territory', iso: 'IO', dialCode: '246', phoneCode: '+246', timezone: 'Indian/Chagos', currency: 'USD' },
  { name: 'Brunei', iso: 'BN', dialCode: '673', phoneCode: '+673', timezone: 'Asia/Brunei', currency: 'BND' },
  { name: 'Bulgaria', iso: 'BG', dialCode: '359', phoneCode: '+359', timezone: 'Europe/Sofia', currency: 'BGN' },
  { name: 'Burkina Faso', iso: 'BF', dialCode: '226', phoneCode: '+226', timezone: 'Africa/Ouagadougou', currency: 'XOF' },
  { name: 'Burundi', iso: 'BI', dialCode: '257', phoneCode: '+257', timezone: 'Africa/Bujumbura', currency: 'BIF' },
  { name: 'Cambodia', iso: 'KH', dialCode: '855', phoneCode: '+855', timezone: 'Asia/Phnom_Penh', currency: 'KHR' },
  { name: 'Cameroon', iso: 'CM', dialCode: '237', phoneCode: '+237', timezone: 'Africa/Douala', currency: 'XAF' },
  { name: 'Canada', iso: 'CA', dialCode: '1', phoneCode: '+1', timezone: 'America/Toronto', currency: 'CAD' },
  { name: 'Cape Verde', iso: 'CV', dialCode: '238', phoneCode: '+238', timezone: 'Atlantic/Cape_Verde', currency: 'CVE' },
  { name: 'Caribbean Netherlands', iso: 'BQ', dialCode: '599', phoneCode: '+599', timezone: 'America/Kralendijk', currency: 'USD' },
  { name: 'Cayman Islands', iso: 'KY', dialCode: '1', phoneCode: '+1', timezone: 'America/Cayman', currency: 'KYD' },
  { name: 'Central African Republic', iso: 'CF', dialCode: '236', phoneCode: '+236', timezone: 'Africa/Bangui', currency: 'XAF' },
  { name: 'Chad', iso: 'TD', dialCode: '235', phoneCode: '+235', timezone: 'Africa/Ndjamena', currency: 'XAF' },
  { name: 'Chile', iso: 'CL', dialCode: '56', phoneCode: '+56', timezone: 'America/Santiago', currency: 'CLP' },
  { name: 'China', iso: 'CN', dialCode: '86', phoneCode: '+86', timezone: 'Asia/Shanghai', currency: 'CNY' },
  { name: 'Colombia', iso: 'CO', dialCode: '57', phoneCode: '+57', timezone: 'America/Bogota', currency: 'COP' },
  { name: 'Comoros', iso: 'KM', dialCode: '269', phoneCode: '+269', timezone: 'Indian/Comoro', currency: 'KMF' },
  { name: 'Congo', iso: 'CD', dialCode: '243', phoneCode: '+243', timezone: 'Africa/Kinshasa', currency: 'CDF' },
  { name: 'Congo', iso: 'CG', dialCode: '242', phoneCode: '+242', timezone: 'Africa/Brazzaville', currency: 'XAF' },
  { name: 'Costa Rica', iso: 'CR', dialCode: '506', phoneCode: '+506', timezone: 'America/Costa_Rica', currency: 'CRC' },
  { name: "Côte d'Ivoire", iso: 'CI', dialCode: '225', phoneCode: '+225', timezone: 'Africa/Abidjan', currency: 'XOF' },
  { name: 'Croatia', iso: 'HR', dialCode: '385', phoneCode: '+385', timezone: 'Europe/Zagreb', currency: 'EUR' },
  { name: 'Cuba', iso: 'CU', dialCode: '53', phoneCode: '+53', timezone: 'America/Havana', currency: 'CUP' },
  { name: 'Curaçao', iso: 'CW', dialCode: '599', phoneCode: '+599', timezone: 'America/Curacao', currency: 'ANG' },
  { name: 'Cyprus', iso: 'CY', dialCode: '357', phoneCode: '+357', timezone: 'Asia/Nicosia', currency: 'EUR' },
  { name: 'Czech Republic', iso: 'CZ', dialCode: '420', phoneCode: '+420', timezone: 'Europe/Prague', currency: 'CZK' },
  { name: 'Denmark', iso: 'DK', dialCode: '45', phoneCode: '+45', timezone: 'Europe/Copenhagen', currency: 'EUR' },
  { name: 'Djibouti', iso: 'DJ', dialCode: '253', phoneCode: '+253', timezone: 'Africa/Djibouti', currency: 'DJF' },
  { name: 'Dominica', iso: 'DM', dialCode: '1767', phoneCode: '+1767', timezone: 'America/Dominica', currency: 'XCD' },
  { name: 'Dominican Republic', iso: 'DO', dialCode: '1', phoneCode: '+1', timezone: 'America/Santo_Domingo', currency: 'DOP' },
  { name: 'Ecuador', iso: 'EC', dialCode: '593', phoneCode: '+593', timezone: 'America/Guayaquil', currency: 'USD' },
  { name: 'Egypt', iso: 'EG', dialCode: '20', phoneCode: '+20', timezone: 'Africa/Cairo', currency: 'EGP' },
  { name: 'El Salvador', iso: 'SV', dialCode: '503', phoneCode: '+503', timezone: 'America/El_Salvador', currency: 'USD' },
  { name: 'Equatorial Guinea', iso: 'GQ', dialCode: '240', phoneCode: '+240', timezone: 'Africa/Malabo', currency: 'XAF' },
  { name: 'Eritrea', iso: 'ER', dialCode: '291', phoneCode: '+291', timezone: 'Africa/Asmara', currency: 'ERN' },
  { name: 'Estonia', iso: 'EE', dialCode: '372', phoneCode: '+372', timezone: 'Europe/Tallinn', currency: 'EUR' },
  { name: 'Ethiopia', iso: 'ET', dialCode: '251', phoneCode: '+251', timezone: 'Africa/Addis_Ababa', currency: 'ETB' },
  { name: 'Faroe Islands', iso: 'FO', dialCode: '298', phoneCode: '+298', timezone: 'Atlantic/Faroe', currency: 'DKK' },
  { name: 'Fiji', iso: 'FJ', dialCode: '679', phoneCode: '+679', timezone: 'Pacific/Fiji', currency: 'FJD' },
  { name: 'Finland', iso: 'FI', dialCode: '358', phoneCode: '+358', timezone: 'Europe/Helsinki', currency: 'EUR' },
  { name: 'France', iso: 'FR', dialCode: '33', phoneCode: '+33', timezone: 'Europe/Paris', currency: 'EUR' },
  { name: 'French Guiana', iso: 'GF', dialCode: '594', phoneCode: '+594', timezone: 'America/Cayenne', currency: 'EUR' },
  { name: 'French Polynesia', iso: 'PF', dialCode: '689', phoneCode: '+689', timezone: 'Pacific/Tahiti', currency: 'XPF' },
  { name: 'Gabon', iso: 'GA', dialCode: '241', phoneCode: '+241', timezone: 'Africa/Libreville', currency: 'XAF' },
  { name: 'Gambia', iso: 'GM', dialCode: '220', phoneCode: '+220', timezone: 'Africa/Banjul', currency: 'GMD' },
  { name: 'Georgia', iso: 'GE', dialCode: '995', phoneCode: '+995', timezone: 'Asia/Tbilisi', currency: 'GEL' },
  { name: 'Germany', iso: 'DE', dialCode: '49', phoneCode: '+49', timezone: 'Europe/Berlin', currency: 'EUR' },
  { name: 'Ghana', iso: 'GH', dialCode: '233', phoneCode: '+233', timezone: 'Africa/Accra', currency: 'GHS' },
  { name: 'Gibraltar', iso: 'GI', dialCode: '350', phoneCode: '+350', timezone: 'Europe/Gibraltar', currency: 'GIP' },
  { name: 'Greece', iso: 'GR', dialCode: '30', phoneCode: '+30', timezone: 'Europe/Athens', currency: 'EUR' },
  { name: 'Greenland', iso: 'GL', dialCode: '299', phoneCode: '+299', timezone: 'America/Nuuk', currency: 'DKK' },
  { name: 'Grenada', iso: 'GD', dialCode: '1473', phoneCode: '+1473', timezone: 'America/Grenada', currency: 'XCD' },
  { name: 'Guadeloupe', iso: 'GP', dialCode: '590', phoneCode: '+590', timezone: 'America/Guadeloupe', currency: 'EUR' },
  { name: 'Guam', iso: 'GU', dialCode: '1671', phoneCode: '+1671', timezone: 'Pacific/Guam', currency: 'USD' },
  { name: 'Guatemala', iso: 'GT', dialCode: '502', phoneCode: '+502', timezone: 'America/Guatemala', currency: 'GTQ' },
  { name: 'Guinea', iso: 'GN', dialCode: '224', phoneCode: '+224', timezone: 'Africa/Conakry', currency: 'GNF' },
  { name: 'Guinea-Bissau', iso: 'GW', dialCode: '245', phoneCode: '+245', timezone: 'Africa/Bissau', currency: 'XOF' },
  { name: 'Guyana', iso: 'GY', dialCode: '592', phoneCode: '+592', timezone: 'America/Guyana', currency: 'GYD' },
  { name: 'Haiti', iso: 'HT', dialCode: '509', phoneCode: '+509', timezone: 'America/Port-au-Prince', currency: 'HTG' },
  { name: 'Honduras', iso: 'HN', dialCode: '504', phoneCode: '+504', timezone: 'America/Tegucigalpa', currency: 'HNL' },
  { name: 'Hong Kong', iso: 'HK', dialCode: '852', phoneCode: '+852', timezone: 'Asia/Hong_Kong', currency: 'HKD' },
  { name: 'Hungary', iso: 'HU', dialCode: '36', phoneCode: '+36', timezone: 'Europe/Budapest', currency: 'HUF' },
  { name: 'Iceland', iso: 'IS', dialCode: '354', phoneCode: '+354', timezone: 'Atlantic/Reykjavik', currency: 'ISK' },
  { name: 'India', iso: 'IN', dialCode: '91', phoneCode: '+91', timezone: 'Asia/Kolkata', currency: 'INR' },
  { name: 'Indonesia', iso: 'ID', dialCode: '62', phoneCode: '+62', timezone: 'Asia/Jakarta', currency: 'IDR' },
  { name: 'Iran', iso: 'IR', dialCode: '98', phoneCode: '+98', timezone: 'Asia/Tehran', currency: 'IRR' },
  { name: 'Iraq', iso: 'IQ', dialCode: '964', phoneCode: '+964', timezone: 'Asia/Baghdad', currency: 'IQD' },
  { name: 'Ireland', iso: 'IE', dialCode: '353', phoneCode: '+353', timezone: 'Europe/Dublin', currency: 'EUR' },
  { name: 'Israel', iso: 'IL', dialCode: '972', phoneCode: '+972', timezone: 'Asia/Jerusalem', currency: 'ILS' },
  { name: 'Italy', iso: 'IT', dialCode: '39', phoneCode: '+39', timezone: 'Europe/Rome', currency: 'EUR' },
  { name: 'Jamaica', iso: 'JM', dialCode: '1876', phoneCode: '+1876', timezone: 'America/Jamaica', currency: 'JMD' },
  { name: 'Japan', iso: 'JP', dialCode: '81', phoneCode: '+81', timezone: 'Asia/Tokyo', currency: 'JPY' },
  { name: 'Jordan', iso: 'JO', dialCode: '962', phoneCode: '+962', timezone: 'Asia/Amman', currency: 'JOD' },
  { name: 'Kazakhstan', iso: 'KZ', dialCode: '7', phoneCode: '+7', timezone: 'Asia/Almaty', currency: 'KZT' },
  { name: 'Kenya', iso: 'KE', dialCode: '254', phoneCode: '+254', timezone: 'Africa/Nairobi', currency: 'KES' },
  { name: 'Kiribati', iso: 'KI', dialCode: '686', phoneCode: '+686', timezone: 'Pacific/Tarawa', currency: 'AUD' },
  { name: 'Kosovo', iso: 'XK', dialCode: '383', phoneCode: '+383', timezone: 'Europe/Belgrade', currency: 'EUR' },
  { name: 'Kuwait', iso: 'KW', dialCode: '965', phoneCode: '+965', timezone: 'Asia/Kuwait', currency: 'KWD' },
  { name: 'Kyrgyzstan', iso: 'KG', dialCode: '996', phoneCode: '+996', timezone: 'Asia/Bishkek', currency: 'KGS' },
  { name: 'Laos', iso: 'LA', dialCode: '856', phoneCode: '+856', timezone: 'Asia/Vientiane', currency: 'LAK' },
  { name: 'Latvia', iso: 'LV', dialCode: '371', phoneCode: '+371', timezone: 'Europe/Riga', currency: 'EUR' },
  { name: 'Lebanon', iso: 'LB', dialCode: '961', phoneCode: '+961', timezone: 'Asia/Beirut', currency: 'LBP' },
  { name: 'Lesotho', iso: 'LS', dialCode: '266', phoneCode: '+266', timezone: 'Africa/Maseru', currency: 'LSL' },
  { name: 'Liberia', iso: 'LR', dialCode: '231', phoneCode: '+231', timezone: 'Africa/Monrovia', currency: 'LRD' },
  { name: 'Libya', iso: 'LY', dialCode: '218', phoneCode: '+218', timezone: 'Africa/Tripoli', currency: 'LYD' },
  { name: 'Liechtenstein', iso: 'LI', dialCode: '423', phoneCode: '+423', timezone: 'Europe/Vaduz', currency: 'CHF' },
  { name: 'Lithuania', iso: 'LT', dialCode: '370', phoneCode: '+370', timezone: 'Europe/Vilnius', currency: 'EUR' },
  { name: 'Luxembourg', iso: 'LU', dialCode: '352', phoneCode: '+352', timezone: 'Europe/Luxembourg', currency: 'EUR' },
  { name: 'Macau', iso: 'MO', dialCode: '853', phoneCode: '+853', timezone: 'Asia/Macau', currency: 'MOP' },
  { name: 'Macedonia', iso: 'MK', dialCode: '389', phoneCode: '+389', timezone: 'Europe/Skopje', currency: 'MKD' },
  { name: 'Madagascar', iso: 'MG', dialCode: '261', phoneCode: '+261', timezone: 'Indian/Antananarivo', currency: 'MGA' },
  { name: 'Malawi', iso: 'MW', dialCode: '265', phoneCode: '+265', timezone: 'Africa/Blantyre', currency: 'MWK' },
  { name: 'Malaysia', iso: 'MY', dialCode: '60', phoneCode: '+60', timezone: 'Asia/Kuala_Lumpur', currency: 'MYR' },
  { name: 'Maldives', iso: 'MV', dialCode: '960', phoneCode: '+960', timezone: 'Indian/Maldives', currency: 'MVR' },
  { name: 'Mali', iso: 'ML', dialCode: '223', phoneCode: '+223', timezone: 'Africa/Bamako', currency: 'XOF' },
  { name: 'Malta', iso: 'MT', dialCode: '356', phoneCode: '+356', timezone: 'Europe/Malta', currency: 'EUR' },
  { name: 'Marshall Islands', iso: 'MH', dialCode: '692', phoneCode: '+692', timezone: 'Pacific/Majuro', currency: 'USD' },
  { name: 'Martinique', iso: 'MQ', dialCode: '596', phoneCode: '+596', timezone: 'America/Martinique', currency: 'EUR' },
  { name: 'Mauritania', iso: 'MR', dialCode: '222', phoneCode: '+222', timezone: 'Africa/Nouakchott', currency: 'MRU' },
  { name: 'Mauritius', iso: 'MU', dialCode: '230', phoneCode: '+230', timezone: 'Indian/Mauritius', currency: 'MUR' },
  { name: 'Mayotte', iso: 'YT', dialCode: '262', phoneCode: '+262', timezone: 'Indian/Mayotte', currency: 'EUR' },
  { name: 'Mexico', iso: 'MX', dialCode: '52', phoneCode: '+52', timezone: 'America/Mexico_City', currency: 'MXN' },
  { name: 'Micronesia', iso: 'FM', dialCode: '691', phoneCode: '+691', timezone: 'Pacific/Chuuk', currency: 'USD' },
  { name: 'Moldova', iso: 'MD', dialCode: '373', phoneCode: '+373', timezone: 'Europe/Chisinau', currency: 'MDL' },
  { name: 'Monaco', iso: 'MC', dialCode: '377', phoneCode: '+377', timezone: 'Europe/Monaco', currency: 'EUR' },
  { name: 'Mongolia', iso: 'MN', dialCode: '976', phoneCode: '+976', timezone: 'Asia/Ulaanbaatar', currency: 'MNT' },
  { name: 'Montenegro', iso: 'ME', dialCode: '382', phoneCode: '+382', timezone: 'Europe/Podgorica', currency: 'EUR' },
  { name: 'Morocco', iso: 'MA', dialCode: '212', phoneCode: '+212', timezone: 'Africa/Casablanca', currency: 'MAD' },
  { name: 'Mozambique', iso: 'MZ', dialCode: '258', phoneCode: '+258', timezone: 'Africa/Maputo', currency: 'MZN' },
  { name: 'Myanmar', iso: 'MM', dialCode: '95', phoneCode: '+95', timezone: 'Asia/Yangon', currency: 'MMK' },
  { name: 'Namibia', iso: 'NA', dialCode: '264', phoneCode: '+264', timezone: 'Africa/Windhoek', currency: 'NAD' },
  { name: 'Nauru', iso: 'NR', dialCode: '674', phoneCode: '+674', timezone: 'Pacific/Nauru', currency: 'AUD' },
  { name: 'Nepal', iso: 'NP', dialCode: '977', phoneCode: '+977', timezone: 'Asia/Kathmandu', currency: 'NPR' },
  { name: 'Netherlands', iso: 'NL', dialCode: '31', phoneCode: '+31', timezone: 'Europe/Amsterdam', currency: 'EUR' },
  { name: 'New Caledonia', iso: 'NC', dialCode: '687', phoneCode: '+687', timezone: 'Pacific/Noumea', currency: 'XPF' },
  { name: 'New Zealand', iso: 'NZ', dialCode: '64', phoneCode: '+64', timezone: 'Pacific/Auckland', currency: 'NZD' },
  { name: 'Nicaragua', iso: 'NI', dialCode: '505', phoneCode: '+505', timezone: 'America/Managua', currency: 'NIO' },
  { name: 'Niger', iso: 'NE', dialCode: '227', phoneCode: '+227', timezone: 'Africa/Niamey', currency: 'XOF' },
  { name: 'Nigeria', iso: 'NG', dialCode: '234', phoneCode: '+234', timezone: 'Africa/Lagos', currency: 'NGN' },
  { name: 'North Korea', iso: 'KP', dialCode: '850', phoneCode: '+850', timezone: 'Asia/Pyongyang', currency: 'KPW' },
  { name: 'Norway', iso: 'NO', dialCode: '47', phoneCode: '+47', timezone: 'Europe/Oslo', currency: 'NOK' },
  { name: 'Oman', iso: 'OM', dialCode: '968', phoneCode: '+968', timezone: 'Asia/Muscat', currency: 'OMR' },
  { name: 'Pakistan', iso: 'PK', dialCode: '92', phoneCode: '+92', timezone: 'Asia/Karachi', currency: 'PKR' },
  { name: 'Palau', iso: 'PW', dialCode: '680', phoneCode: '+680', timezone: 'Pacific/Palau', currency: 'USD' },
  { name: 'Palestine', iso: 'PS', dialCode: '970', phoneCode: '+970', timezone: 'Asia/Gaza', currency: 'ILS' },
  { name: 'Panama', iso: 'PA', dialCode: '507', phoneCode: '+507', timezone: 'America/Panama', currency: 'PAB' },
  { name: 'Papua New Guinea', iso: 'PG', dialCode: '675', phoneCode: '+675', timezone: 'Pacific/Port_Moresby', currency: 'PGK' },
  { name: 'Paraguay', iso: 'PY', dialCode: '595', phoneCode: '+595', timezone: 'America/Asuncion', currency: 'PYG' },
  { name: 'Peru', iso: 'PE', dialCode: '51', phoneCode: '+51', timezone: 'America/Lima', currency: 'PEN' },
  { name: 'Philippines', iso: 'PH', dialCode: '63', phoneCode: '+63', timezone: 'Asia/Manila', currency: 'PHP' },
  { name: 'Poland', iso: 'PL', dialCode: '48', phoneCode: '+48', timezone: 'Europe/Warsaw', currency: 'PLN' },
  { name: 'Portugal', iso: 'PT', dialCode: '351', phoneCode: '+351', timezone: 'Europe/Lisbon', currency: 'EUR' },
  { name: 'Puerto Rico', iso: 'PR', dialCode: '1', phoneCode: '+1', timezone: 'America/Puerto_Rico', currency: 'USD' },
  { name: 'Qatar', iso: 'QA', dialCode: '974', phoneCode: '+974', timezone: 'Asia/Qatar', currency: 'QAR' },
  { name: 'Romania', iso: 'RO', dialCode: '40', phoneCode: '+40', timezone: 'Europe/Bucharest', currency: 'RON' },
  { name: 'Russia', iso: 'RU', dialCode: '7', phoneCode: '+7', timezone: 'Europe/Moscow', currency: 'RUB' },
  { name: 'Rwanda', iso: 'RW', dialCode: '250', phoneCode: '+250', timezone: 'Africa/Kigali', currency: 'RWF' },
  { name: 'Saint Lucia', iso: 'LC', dialCode: '1758', phoneCode: '+1758', timezone: 'America/St_Lucia', currency: 'XCD' },
  { name: 'Saint Pierre & Miquelon', iso: 'PM', dialCode: '508', phoneCode: '+508', timezone: 'America/Miquelon', currency: 'EUR' },
  { name: 'Saint Vincent and the Grenadines', iso: 'VC', dialCode: '1784', phoneCode: '+1784', timezone: 'America/St_Vincent', currency: 'XCD' },
  { name: 'Samoa', iso: 'WS', dialCode: '685', phoneCode: '+685', timezone: 'Pacific/Apia', currency: 'WST' },
  { name: 'San Marino', iso: 'SM', dialCode: '378', phoneCode: '+378', timezone: 'Europe/San_Marino', currency: 'EUR' },
  { name: 'Sao Tome and Principe', iso: 'ST', dialCode: '239', phoneCode: '+239', timezone: 'Africa/Sao_Tome', currency: 'STN' },
  { name: 'Saudi Arabia', iso: 'SA', dialCode: '966', phoneCode: '+966', timezone: 'Asia/Riyadh', currency: 'SAR' },
  { name: 'Senegal', iso: 'SN', dialCode: '221', phoneCode: '+221', timezone: 'Africa/Dakar', currency: 'XOF' },
  { name: 'Serbia', iso: 'RS', dialCode: '381', phoneCode: '+381', timezone: 'Europe/Belgrade', currency: 'RSD' },
  { name: 'Seychelles', iso: 'SC', dialCode: '248', phoneCode: '+248', timezone: 'Indian/Mahe', currency: 'SCR' },
  { name: 'Sierra Leone', iso: 'SL', dialCode: '232', phoneCode: '+232', timezone: 'Africa/Freetown', currency: 'SLE' },
  { name: 'Singapore', iso: 'SG', dialCode: '65', phoneCode: '+65', timezone: 'Asia/Singapore', currency: 'SGD' },
  { name: 'Slovakia', iso: 'SK', dialCode: '421', phoneCode: '+421', timezone: 'Europe/Bratislava', currency: 'EUR' },
  { name: 'Slovenia', iso: 'SI', dialCode: '386', phoneCode: '+386', timezone: 'Europe/Ljubljana', currency: 'EUR' },
  { name: 'Solomon Islands', iso: 'SB', dialCode: '677', phoneCode: '+677', timezone: 'Pacific/Guadalcanal', currency: 'SBD' },
  { name: 'Somalia', iso: 'SO', dialCode: '252', phoneCode: '+252', timezone: 'Africa/Mogadishu', currency: 'SOS' },
  { name: 'South Africa', iso: 'ZA', dialCode: '27', phoneCode: '+27', timezone: 'Africa/Johannesburg', currency: 'ZAR' },
  { name: 'South Korea', iso: 'KR', dialCode: '82', phoneCode: '+82', timezone: 'Asia/Seoul', currency: 'KRW' },
  { name: 'South Sudan', iso: 'SS', dialCode: '211', phoneCode: '+211', timezone: 'Africa/Juba', currency: 'SSP' },
  { name: 'Spain', iso: 'ES', dialCode: '34', phoneCode: '+34', timezone: 'Europe/Madrid', currency: 'EUR' },
  { name: 'Sri Lanka', iso: 'LK', dialCode: '94', phoneCode: '+94', timezone: 'Asia/Colombo', currency: 'LKR' },
  { name: 'Sudan', iso: 'SD', dialCode: '249', phoneCode: '+249', timezone: 'Africa/Khartoum', currency: 'SDG' },
  { name: 'Suriname', iso: 'SR', dialCode: '597', phoneCode: '+597', timezone: 'America/Paramaribo', currency: 'SRD' },
  { name: 'Sweden', iso: 'SE', dialCode: '46', phoneCode: '+46', timezone: 'Europe/Stockholm', currency: 'SEK' },
  { name: 'Switzerland', iso: 'CH', dialCode: '41', phoneCode: '+41', timezone: 'Europe/Zurich', currency: 'CHF' },
  { name: 'Syria', iso: 'SY', dialCode: '963', phoneCode: '+963', timezone: 'Asia/Damascus', currency: 'SYP' },
  { name: 'Taiwan', iso: 'TW', dialCode: '886', phoneCode: '+886', timezone: 'Asia/Taipei', currency: 'TWD' },
  { name: 'Tajikistan', iso: 'TJ', dialCode: '992', phoneCode: '+992', timezone: 'Asia/Dushanbe', currency: 'TJS' },
  { name: 'Tanzania', iso: 'TZ', dialCode: '255', phoneCode: '+255', timezone: 'Africa/Dar_es_Salaam', currency: 'TZS' },
  { name: 'Thailand', iso: 'TH', dialCode: '66', phoneCode: '+66', timezone: 'Asia/Bangkok', currency: 'THB' },
  { name: 'Timor-Leste', iso: 'TL', dialCode: '670', phoneCode: '+670', timezone: 'Asia/Dili', currency: 'USD' },
  { name: 'Togo', iso: 'TG', dialCode: '228', phoneCode: '+228', timezone: 'Africa/Lome', currency: 'XOF' },
  { name: 'Tonga', iso: 'TO', dialCode: '676', phoneCode: '+676', timezone: 'Pacific/Tongatapu', currency: 'TOP' },
  { name: 'Trinidad and Tobago', iso: 'TT', dialCode: '1868', phoneCode: '+1868', timezone: 'America/Port_of_Spain', currency: 'TTD' },
  { name: 'Tunisia', iso: 'TN', dialCode: '216', phoneCode: '+216', timezone: 'Africa/Tunis', currency: 'TND' },
  { name: 'Turkey', iso: 'TR', dialCode: '90', phoneCode: '+90', timezone: 'Europe/Istanbul', currency: 'TRY' },
  { name: 'Turkmenistan', iso: 'TM', dialCode: '993', phoneCode: '+993', timezone: 'Asia/Ashgabat', currency: 'TMT' },
  { name: 'Tuvalu', iso: 'TV', dialCode: '688', phoneCode: '+688', timezone: 'Pacific/Funafuti', currency: 'AUD' },
  { name: 'Uganda', iso: 'UG', dialCode: '256', phoneCode: '+256', timezone: 'Africa/Kampala', currency: 'UGX' },
  { name: 'Ukraine', iso: 'UA', dialCode: '380', phoneCode: '+380', timezone: 'Europe/Kyiv', currency: 'UAH' },
  { name: 'United Arab Emirates', iso: 'AE', dialCode: '971', phoneCode: '+971', timezone: 'Asia/Dubai', currency: 'AED' },
  { name: 'United Kingdom', iso: 'GB', dialCode: '44', phoneCode: '+44', timezone: 'Europe/London', currency: 'GBP' },
  { name: 'United States', iso: 'US', dialCode: '1', phoneCode: '+1', timezone: 'America/New_York', currency: 'USD' },
  { name: 'Uruguay', iso: 'UY', dialCode: '598', phoneCode: '+598', timezone: 'America/Montevideo', currency: 'UYU' },
  { name: 'Uzbekistan', iso: 'UZ', dialCode: '998', phoneCode: '+998', timezone: 'Asia/Tashkent', currency: 'UZS' },
  { name: 'Vanuatu', iso: 'VU', dialCode: '678', phoneCode: '+678', timezone: 'Pacific/Efate', currency: 'VUV' },
  { name: 'Vatican City', iso: 'VA', dialCode: '39', phoneCode: '+39', timezone: 'Europe/Vatican', currency: 'EUR' },
  { name: 'Venezuela', iso: 'VE', dialCode: '58', phoneCode: '+58', timezone: 'America/Caracas', currency: 'VES' },
  { name: 'Vietnam', iso: 'VN', dialCode: '84', phoneCode: '+84', timezone: 'Asia/Ho_Chi_Minh', currency: 'VND' },
  { name: 'Western Sahara', iso: 'EH', dialCode: '212', phoneCode: '+212', timezone: 'Africa/El_Aaiun', currency: 'MAD' },
  { name: 'Yemen', iso: 'YE', dialCode: '967', phoneCode: '+967', timezone: 'Asia/Aden', currency: 'YER' },
  { name: 'Zambia', iso: 'ZM', dialCode: '260', phoneCode: '+260', timezone: 'Africa/Lusaka', currency: 'ZMW' },
  { name: 'Zimbabwe', iso: 'ZW', dialCode: '263', phoneCode: '+263', timezone: 'Africa/Harare', currency: 'ZWL' },
];

/** Phone code + currency by ISO2. */
export const COUNTRY_MAP: Record<string, { phoneCode: string; currency: string }> =
  Object.fromEntries(
    COUNTRY_LIST.map((c) => [c.iso, { phoneCode: c.phoneCode, currency: c.currency }]),
  );

/** Primary IANA timezone by ISO2. */
export const COUNTRY_TIMEZONE_MAP: Record<string, string> = Object.fromEntries(
  COUNTRY_LIST.map((c) => [c.iso, c.timezone]),
);
